name: Backend CI - Build .NET

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/DoacoesONG/**' # Aciona apenas quando o cÃ³digo no backend muda
  pull_request:
    branches:
      - develop
      - main # O CI agora serÃ¡ executado para Pull Requests na main
    paths:
      - 'backend/DoacoesONG/**'

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do CÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Setup do .NET (VersÃ£o 8.0)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' 

      - name: ğŸ“¦ Restore de DependÃªncias (Usando SLN)
        # O comando dotnet restore no .sln restaura todas as dependÃªncias dos projetos na soluÃ§Ã£o.
        run: dotnet restore DoacaoMariaClaro.sln
        
      - name: ğŸ—ï¸ Compilar o Projeto Backend (Usando SLN)
        # O comando dotnet build no .sln compila todos os projetos na soluÃ§Ã£o.
        run: dotnet build DoacaoMariaClaro.sln --configuration Release --no-restore